#ifndef _GLOBAL_MACRO_H_
#define _GLOBAL_MACRO_H_

#define DEBUG 1
#define UNHILIGHT (1 && DEBUG)
#define LEXICAL_ANALYSIS_DEBUG (1 && DEBUG)
#define GRAMMER_ANALYSIS_DEBUG (1 && DEBUG)
#define GRAMMER_ANALYSIS_OUTPUT 1
#define LEXICAL_ANALYSIS_OUTPUT 1

#endif // !_GLOBAL_MACRO_H_